# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e8d41b5c551bd4b2a8f7315ab5f54fb6dbdaae348c4caf1152ccd544901b08d5d2103930e6c3a4e72c20dc5deb03affaeac0fd1ccebb2a6be288647f7fcefe

test:
  secret_key_base: 1ca6346f0240ebb9f3cf1ce298b3fc54427f76686cd59c711b8fa8028ecf9d5271c760f14709157f00c76c79332851b252f95bb56f13613e34dd7767d7453812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
